update series set description_serie='Une ville cauchemardesque du centre des Etats-Unis piège tous ceux qui y entrent. Alors que les habitants, malgré eux, se battent pour conserver un sentiment de normalité et cherchent une issue, ils doivent également survivre aux menaces de la forêt environnante, notamment aux créatures terrifiantes qui sortent lorsque le soleil se couche.',
genre=' Epouvante-horreur, Science fiction',
pays='U.S.A',realisateur=' John Griffin',temps='60min',
cast=' Harold Perrineau, Catalina Sandino Moreno, Eion Bailey',
annee=2022 where titre='From';



update series set description_serie='A présent étudiante à la singulière Nevermore Academy, Wednesday Addams tente de s\'adapter auprès des autres élèves tout en enquêtant à la suite d\'une série de meurtres qui terrorise la ville...',
genre='Comédie, Fantastique, Thriller', pays='U.S.A',
realisateur='Alfred Gough, Miles Millar',temps='45min', cast='Jenna Ortega, Gwendoline Christie, Riki Lindhome', annee=2022 where titre='Mercredi';



update series set description_serie='Fin des années 1980. Le parcours de deux frères, Demetrius "Big Meech" Flenory et Terry "Southwest T" Flenory, ayant grandi avec les codes des rues de Détroit. Ils ont donné naissance à l\'une des familles criminelles les plus influentes des Etats-Unis grâce au commerce de la drogue et parallèlement à leur lien avec le monde du hip-hop.',
genre=' Drame, Thriller, Biopic, Musical', pays='U.S.A',realisateur='Randy Huggins',
temps='60min', cast=' Russell Hornsby, Russell Hornsby, Da\'Vinchi', annee=2021 where titre='Black Mafia Family';



update series set description_serie='Trois étudiants de première année à l\'université de Blue Mountain State doivent rapidement s\'adapter à leur nouvelle vie et jongler entre le football, les filles, les cours et le sort réservé aux premières années.',genre='Comédie',
pays='U.S.A',realisateur=' Chris Romano, Eric Falconer',temps='22min', cast=' Ed Marinaro, Darin Brooks, Chris Romano (II)',
annee=2010 where titre='Blue Mountain State';

update series set description_serie='Jeune et séduisant acteur, Vincent Chase rencontre très vite le succès et devient une star adulée à Hollywood. Soucieux de ne pas oublier ses origines, Vince s\'entoure de ses amis d\'enfance originaires comme lui du Queens, l\'un des quartiers pauvres de New York. Avec eux, il partage cette nouvelle aventure dans ce monde de strass et de paillettes.',genre='Comédie, Drame', pays='U.S.A',realisateur='Doug Ellin',temps='25min', cast=' Adrian Grenier, Kevin Connolly, Kevin Dillon', annee=2004 where titre='Entourage';

update series set description_serie='Comment reconquérir le cœur de votre petite amie qui vous a quitté pour le dealer de l\'école ? Pour Moritz, la réponse est claire : vendre de meilleures drogues que lui !',genre='Comédie', pays='Allemagne',realisateur='Philipp Käßbohrer, Matthias Murmann',temps='30min', cast='Maximilian Mundt, Maximilian Mundt, Danilo Kamperidis', annee=2019 where titre='How To Sell Drugs Online (Fast)';

update series set description_serie='Huit voleurs font une prise d\'otages dans la Maison royale de la Monnaie d\'Espagne, tandis qu\'un génie du crime manipule la police pour mettre son plan à exécution.',genre='Drame,Action', pays='Espagne',realisateur='Álex Pina',temps='45min', cast='Úrsula Corberó, Álvaro Morte, Itziar Ituño', annee=2017 where titre='La Casa De Papel';

update series set description_serie='Les aventures de Hope Mikaelson, la fille tribride du vampire originel Klaus, et de Lizzie et Josie Saltzman, les jumelles d\'Alaric, au sein de l\'école Salvatore de Mystic Falls, réservée aux jeunes vampires, sorciers, et autres êtres surnaturels.',genre=' Aventure, Drame, Fantastique', pays='U.S.A',realisateur='Julie Plec',temps='42min', cast='Danielle Rose Russell, Danielle Rose Russell, Aria Shahghasemi', annee=2018 where titre='Legacies';

update series set description_serie='Description',genre='Genre', pays='Pays',realisateur='Realisateur',temps='Temps', cast='cast', annee=2000 where titre='Love 101';

update series set description_serie='Lassé et mécontent de sa position de "Seigneur des Enfers", Lucifer Morningstar démissionne et abandonne le trône de son royaume pour la bouillonnante et non moins impure Los Angeles. Dans la Cité des anges, l\'ex maître diabolique est le patron d\'un nightclub baptisé "Lux". Quand une star de la Pop est sauvagement assassinée sous ses yeux, il décide de partir à la recherche du coupable et croise sur sa route Chloe Decker, une femme flic qui résiste à ses charmes et lui met constamment des bâtons dans les roues.',genre=' Drame, Fantastique, Policier', pays='U.S.A',realisateur='Tom Kapinos',temps='42 min', cast='Tom Ellis, Lauren German, Kevin Alejandro', annee=2016 where titre='Lucifer';

update series set description_serie='Michael Kyle est un mari aimant et un père de famille comblé. Mais il n\'est pas toujours facile d\'élever trois enfants. Entre un fils passionné de musique rap, une fille adolescente qui lui cause bien des soucis et la benjamine qui veut toujours avoir le dernier mot, on ne s\'ennuie pas avec la famille Kyle.',genre='Comédie', pays='U.S.A',realisateur='Damon Wayans, Don Reo',temps='22min', cast='Damon Wayans, Tisha Campbell, Jennifer Freeman', annee=2001 where titre='Ma Famille D\'abord';

update series set description_serie='Loin d\’un simple biopic de Pablo Escobar, Narcos retrace la lutte acharnée des États-Unis et de la Colombie contre le cartel de la drogue de Medellín, l\’organisation la plus lucrative et impitoyable de l\’histoire criminelle moderne. En multipliant les points de vue — policier, politique, judiciaire et personnel — la série dépeint l\’essor du trafic de cocaïne et le bras de fer sanglant engagé avec les narcotrafiquants qui contrôlent le marché avec violence et ingéniosité.',genre=' Drame, Policier, Thriller, Biopic', pays='U.S.A',realisateur='Carlo Bernard, Chris Brancato, Doug Miro',temps='52min', cast='Pedro Pascal, Damián Alcázar, Francisco Denis', annee=2015 where titre='Narcos';

update series set description_serie='Monkey D. Luffy est un jeune aventurier qui a toujours rêvé d\'une vie de liberté. Quittant son village, il se lance dans un périlleux voyage à la recherche d\'un trésor mythique, le One Piece, afin de devenir le roi des pirates ! Mais pour trouver ce fameux butin, Luffy devra assembler l\'équipage de ses rêves puis dénicher un navire, quadriller les océans, se défaire de la Marine à ses trousses et se montrer meilleur stratège que les dangereux rivaux qui l\'attendent à chaque étape.',genre=' Aventure, Fantastique, Action', pays='U.S.A',realisateur=' Steven Maeda, Matt Owens',temps='55min', cast='Iñaki Godoy, Mackenyu, Emily Rudd', annee=2023 where titre='One Piece';

update series set description_serie='En 1919, à Birmingham, soldats, révolutionnaires politiques et criminels combattent pour se faire une place dans le paysage industriel de l\'après-Guerre. Le Parlement s\'attend à une violente révolte, et Winston Churchill mobilise des forces spéciales pour contenir les menaces. La famille Shelby compte parmi les membres les plus redoutables. Surnommés les "Peaky Blinders" par rapport à leur utilisation de lames de rasoir cachées dans leurs casquettes, ils tirent principalement leur argent de paris et de vol. Tommy Shelby, le plus dangereux de tous, va devoir faire face à l\'arrivée de Campbell, un impitoyable chef de la police qui a pour mission de nettoyer la ville. Ne doit-il pas se méfier tout autant de la ravissante Grace Burgess ? Fraîchement installée dans le voisinage, celle-ci semble cacher un mystérieux passé et un dangereux secret.',genre='Drame, Historique, Policier', pays='Grande-Bretagne',realisateur='Steven Knight',temps='52min', cast='Cillian Murphy, Cillian Murphy, Natasha O\'Keeffe', annee=2013 where titre='Peaky Blinders';


update series set description_serie='Propriétaire d\’un nightclub new-yorkais très populaire, James "Ghost" St. Patrick entend développer son empire. Seulement sa double-vie à la tête d\'un des réseaux de drogue les plus importants de la ville pourrait devenir un handicap. Vouloir mettre un terme à sa carrière de criminel risque de mettre en danger son mariage, sa famille et ses affaires.',genre=' Drame, Judiciaire', pays='U.S.A',realisateur=' Courtney Kemp Agboh',temps='52min', cast='Omari Hardwick, Joseph Sikora, Lela Loren', annee=2014 where titre='Power';

update series set description_serie='Tariq St. Patrick est tiraillé entre sa nouvelle vie et son désir de se libérer de l\’héritage paternel tout en faisant face à la pression croissante de sauver sa famille, dont sa mère Tasha, accusée du meurtre commis par son fils. Sans parler de la rigueur académique que lui impose ses professeurs de l\’Université Ivy League. Vraiment seul pour la première fois de sa vie, Tariq est obligé de partager son temps entre les cours et les petits boulots pour pouvoir payer Davis MacLean, l\’avocat de la défense avide de renommée, seul espoir pour Tasha de sortir de prison et d\’échapper aux poursuites du nouveau procureur Cooper Saxe. Sans meilleures options, Tarik se tourne vers une activité familière – le trafic de drogue – et se frotte à une dangereuse famille dirigée d\’une main de maître par Monet Stewart Tejada. Tariq tente de trouver un équilibre entre son commerce illégal, ses notes, sa vie amoureuse et sa famille. Il découvre que la seule façon d\’éviter le même sort que son père est de le surpasser.',genre='Drame,Policier', pays='U.S.A',realisateur='Courtney Kemp Agboh',temps='42min', cast=' Michael Rainey Jr., Michael Rainey Jr., Shane Johnson', annee=2020 where titre='Power Book II Ghost';

update series set description_serie='Ancienne recrue de l\'armée américaine, Jack Reacher s\'est retiré de la police militaire. Son voyage à travers le pays l\'amène à s\'impliquer dans de périlleuses enquêtes. D\'après la série d\'ouvrages "Jack Reacher", de Lee Child.',genre='Policier, Thriller, Action', pays='U.S.A',realisateur='Nick Santora',temps='60min', cast='Alan Ritchson, Maria Sten, Serinda Swan', annee=2022 where titre='Reacher';

update series set description_serie='La rebelle Maeve entraîne Otis, un ado vierge mais doté d\'une mère sexologue, dans la création d\'une cellule de thérapie sexuelle clandestine au sein de leur lycée...',genre='Comédie, Drame', pays='Grande-Bretagne',realisateur='Laurie Nunn',temps='50min', cast='Asa Butterfield, Asa Butterfield, Gillian Anderson', annee=2019 where titre='Sex Education';

update series set description_serie='Une femme se trouve au coeur d\'un triangle amoureux entre son mari et son passif sentimental et sexuel.',genre='Comédie, Drame, Romance', pays='U.S.A',realisateur='Stacy Rukeyser',temps='50min', cast='Sarah Shahi, Mike Vogel, Adam Demos', annee=2021 where titre='Sex Life';

update series set description_serie='Pour les enfants Gallagher, la vie est tout sauf un long fleuve tranquille... Fiona, l\'aînée, âgée de 20 ans, élève du mieux possible sa soeur et ses quatre frères. Leur mère, Monica, les a abandonnés pour refaire sa vie avec une femme. Quant à leur père, Frank, paumé, chômeur et alcoolique, il dilapide l\'argent des allocations familiales...',genre='Comédie, Drame', pays='U.S.A',realisateur='Paul Abbott',temps='45min', cast=' William H. Macy, Jeremy Allen White, Ethan Cutkosky', annee=2011 where titre='Shameless';

update series set description_serie='Comment le trafic du crack a changé la ville de Los Angeles dans les années 1980... Pauvreté, violence, drogue et prostitution constituent l\’ADN de la ville, tandis que la ségrégation raciale bat toujours son plein.',genre='Drame', pays='U.S.A',realisateur='Eric Amadio, John Singleton, Dave Andron',temps='58min', cast=' Damson Idris, Damson Idris, Carter Hudson', annee=2017 where titre='Snowfall';

update series set description_serie='Tentés par un prix alléchant en cas de victoire, des centaines de joueurs désargentés acceptent de s\'affronter lors de jeux pour enfants aux enjeux mortels.',genre='Drame Thriller', pays='Corée du Sud',realisateur='Hwang Dong-hyuk',temps='60min', cast='Jung-jae Lee, Park Hae-Soo, Jung Ho-Yeon', annee=2021 where titre='Squid Game';

update series set description_serie='Lucas alias Lux, génie de l\'informatique, entre dans la meilleure école d\'ingénieur de France. Lors de la première soirée organisée par le BDE, il se fait bizuter et humilier par les étudiants les plus en vue du campus. Pour se venger, il hacke leurs téléphones et ordinateurs pour les stalker, connaître tous leurs secrets, intégrer leur bande, et les manipuler de l\'intérieur. Il devient celui qu\'il a toujours rêvé d\'être, avant que tout ne se retourne contre lui.',genre=' Drame, Thriller', pays='France',realisateur='Simon Bouisson, Jean-Charles Paugam, Victor Rodenbach',temps='26min', cast='Théo Fernandez, Théo Fernandez, Carmen Kassovitz', annee=2020 where titre='STALK';

update series set description_serie='Le vampire originel Klaus fait son retour au Vieux Carré, un quartier français de la Nouvelle Orléans. Dans cette ville qu\'il a aidé à construire quelques siècles plus tôt, il y retrouve son ancien protégé, le diabolique et charismatique Marcel. Dans l\'espoir d\'aider son jeune frère à trouver la rédemption, Elijah est contraint de s\’allier avec des ennemis de Marcel...',genre='Drame, Epouvante-horreur, Fantastique', pays='U.S.A',realisateur='Julie Plec',temps='42min', cast='Joseph Morgan, Daniel Gillies, Phoebe Tonkin', annee=2013 where titre='The Originals';

update series set description_serie='Quatre mois après le tragique accident de voiture qui a tué leurs parents, Elena Gilbert, 17 ans, et son frère Jeremy, 15 ans, essaient encore de s\'adapter à cette nouvelle réalité. Belle et populaire, l\'adolescente poursuit ses études au Mystic Falls High en s\'efforçant de masquer son chagrin. Elena est immédiatement fascinée par Stefan et Damon Salvatore, deux frères que tout oppose. Elle ne tarde pas à découvrir qu\'ils sont en fait des vampires...',genre='Drame, Fantastique, Romance', pays='U.S.A',realisateur='Julie Plec, Kevin Williamson',temps='42min', cast='Paul Wesley, Ian Somerhalder, Candice King', annee=2009 where titre='The Vampire Diaries';

update series set description_serie='Un homme peut voir son mode de vie s\'améliorer s\’il accepte de livrer un colis en traversant une contrée sauvage et désolée. Seulement sur le trajet, il faudra compter sur le terrifiant Sweet Tooth et son camion, qui viendront perturber le parcours pour donner lieu à des combats entre véhicules.',genre='Comédie, Action', pays='U.S.A',realisateur='Michael Jonathan Smith',temps='30min', cast='Anthony Mackie, Stephanie Beatriz, Joe Seanoa', annee=2023 where titre='Twisted Metal';

update series set description_serie='Scandinavie, à la fin du 8ème siècle. Ragnar Lodbrok, un jeune guerrier viking, est avide d\'aventures et de nouvelles conquêtes. Lassé des pillages sur les terres de l\'Est, il se met en tête d\'explorer l\'Ouest par la mer. Malgré la réprobation de son chef, Haraldson, il se fie aux signes et à la volonté des dieux, en construisant une nouvelle génération de vaisseaux, plus légers et plus rapides...',genre='Aventure, Drame, Historique', pays='Canada, Irlande',realisateur='Michael Hirst',temps='52min', cast='Alex Høgh Andersen, Marco Ilsø, Jordan Patrick Smith', annee=2013 where titre='Vikings';

update series set description_serie='Une jeune femme d\'une vingtaine d\'années se réveille à la morgue, vivante, avec un artefact implanté dans le dos. Elle découvre qu\'elle est maintenant membre d\'un ordre ancien qui s\'est donné pour mission de combattre les démons sur Terre.',genre='Drame, Fantastique, Action', pays='U.S.A',realisateur='Simon Barry',temps='45min', cast='Alba Baptista, Thekla Reuten, Lorena Andrea', annee=2022 where titre='Warrior Nun';
